export const pagesRoutes = [
  ["v-8daa1a0e","/",{"title":"博客主页","icon":"home","type":"home","readingTime":{"minutes":0.76,"words":228},"excerpt":"<!-- 这是一个博客主页的案例。 要使用此布局，你应该在页面前端设置 layout: Blog 和 home: true。 相关配置文档请见 博客主页。 -->","date":"2022-09-11T14:07:04.000Z"},["/index.html","/README.md"]],
  ["v-79fdd481","/home.html",{"title":"项目主页","icon":"home","type":"home","readingTime":{"minutes":2.61,"words":782},"excerpt":"这是项目主页的案例。你可以在这里放置你的主体内容。 想要使用此布局，你需要在页面 front matter 中设置 home: true。 配置项的相关说明详见 项目主页配置。","date":"2022-09-11T14:07:04.000Z"},["/home","/home.md"]],
  ["v-0a1c5cb7","/posts/article/2022-09/vuepress.html",{"title":"使用 vuepress 搭建博客，专注文档内容","type":"article","readingTime":{"minutes":0.47,"words":140},"excerpt":"<h1 id=\"使用-vuepress-搭建博客-专注文档内容\" tabindex=\"-1\"><a class=\"header-anchor\" href=\"#使用-vuepress-搭建博客-专注文档内容\" aria-hidden=\"true\">#</a> 使用 vuepress 搭建博客，专注文档内容</h1>\n<p>由于近期在开发一个外部对接的项目，公司也没有提供统一对外提供的<code v-pre>文档平台</code>，就得靠自己去找个简单明了的工具了, 一共用过两个工具 <code v-pre>gitbook</code>, <code v-pre>vuepress</code>; 两个工具都有使用，我简单介绍下这两个工具的使用</p>\n","date":"2022-09-10T00:00:00.000Z","localizedDate":"2022年9月10日","category":["vuepress","blog"],"tag":["博客"]},["/posts/article/2022-09/vuepress","/posts/article/2022-09/vuepress.md"]],
  ["v-3706649a","/404.html",{"title":"","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/404"]],
  ["v-5bc93818","/category/",{"title":"分类","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/index.html"]],
  ["v-744d024e","/tag/",{"title":"标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/index.html"]],
  ["v-e52c881c","/article/",{"title":"文章","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/article/index.html"]],
  ["v-75ed4ea4","/encrypted/",{"title":"加密","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/encrypted/index.html"]],
  ["v-d804e652","/slide/",{"title":"幻灯片","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/slide/index.html"]],
  ["v-154dc4c4","/star/",{"title":"收藏","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/star/index.html"]],
  ["v-01560935","/timeline/",{"title":"时间轴","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/timeline/index.html"]],
  ["v-43d7543a","/category/vuepress/",{"title":"vuepress 分类","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/vuepress/index.html"]],
  ["v-3a134560","/tag/%E5%8D%9A%E5%AE%A2/",{"title":"博客 标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/博客/","/tag/%E5%8D%9A%E5%AE%A2/index.html"]],
  ["v-57c5dbb5","/category/blog/",{"title":"blog 分类","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/blog/index.html"]],
]
